dudaji-vn/middo-translate

- src/components/translate-editor/translate-middle.tsx
> Fix case sensitivity issue in TranslateMiddle

- src/components/translate-editor/translate-middle.tsx
> Fix conditional statement in TranslateMiddle

- src/app/page.tsx
- src/components/translate-editor/compare-bar.tsx
- src/components/translate-editor/translate-editor.tsx
- src/components/translate-option-bar/translate-option-bar.tsx
voice input in TranslateOptionBar
> Add isListening prop to TranslateEditor and handle

- package.json
- src/components/translate-option-bar/style.css
- src/components/translate-option-bar/translate-option-bar.tsx
- src/hooks/use-wave-form.ts
- yarn.lock
dependencies, update translate-option-bar styles
and functionality
> Add wavesurfer.js

- src/components/translate-editor/translate-result.tsx
accessibility and user experience.
> Refactor TranslateResult component to improve

- src/components/list-languages/list-languages.tsx
- src/components/translate-editor/edit-button.tsx
- src/components/translate-editor/translate-middle-editor.tsx
- src/components/translate-editor/translate-middle.tsx
> Refactor language list and translate editor

- src/components/online-conversation/chat/chat-context.tsx
- src/components/online-conversation/chat/header.tsx
- src/components/online-conversation/chat/side-chat/member-list.tsx
- src/components/online-conversation/chat/side-chat/side-chat-body.tsx
- src/components/online-conversation/room-creator-submit.tsx
- src/database/models/room.ts
- src/types/room.ts
> Fix room host information in chat header and

- src/app/(room-layout)/online-conversation/[code]/page.tsx
- src/app/(room-layout)/online-conversation/not-found/page.tsx
- src/configs/route-name.ts
> Add redirect to not-found page in RoomConversation

- src/app/(main-layout)/(online-conversation)/online-conversation/create/page.tsx
- src/app/(main-layout)/(online-conversation)/online-conversation/join/[code]/page.tsx
- src/app/(main-layout)/(online-conversation)/online-conversation/page.tsx
- src/app/(main-layout)/(online-conversation)/online-conversation/style.css
- src/app/(room-layout)/online-conversation/not-found/page.tsx
- src/components/button/button.tsx
- src/components/layout/header.tsx
- src/components/online-conversation/chat/side-chat/side-footer.tsx
> Add Image component to display images in

- src/components/online-conversation/join/room-joiner-submit.tsx
> Remove unused code and update socketId in

- src/app/(main-layout)/(protected)/talk/layout.tsx
- src/app/(main-layout)/layout.tsx
- src/features/call/components/call-bottom.tsx
- src/features/call/components/chat-thread.tsx
- src/features/call/components/common/focus-video-item.tsx
- src/features/call/components/common/video-item.tsx
- src/features/call/components/receive-call.tsx
- src/features/call/components/video-call-drag-wrapper.tsx
- src/features/call/components/video-call-main.tsx
- src/features/call/hooks/use-load-stream.ts
- src/features/chat/rooms/components/room-box/room-box-footer.tsx
- src/providers/app.provider.tsx
> Add layout for chat thread

- src/features/call/components/receive-call.tsx
- src/features/call/components/video-call-drag-wrapper.tsx
- src/features/call/components/video-call-main.tsx
- src/features/chat/rooms/components/room-box/room-box-header/room-box-header.tsx
- src/services/call.servide.ts
Add message when create meeting
> Add message when create meeting

- src/features/call/components/chat-thread.tsx
- src/features/call/context/video-call-context.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar.tsx
- src/features/chat/rooms/hooks/use-check-have-meeting.ts
Refactor useCheckHaveMeeting hook
> Refactor useCheckHaveMeeting hook

- src/features/call/components/call-bottom.tsx
- src/features/call/components/common/doodle-area.tsx
- src/features/call/components/common/modal/modal-leave-call.tsx
- src/features/call/components/common/modal/modal-switch-room.tsx
- src/features/call/components/index.tsx
- src/features/call/components/video-call-drag-wrapper.tsx
- src/features/call/components/video-call-main.tsx
- src/features/call/constant/default-user-call-state.ts
- src/features/call/context/video-call-context.tsx
- src/features/call/hooks/socket/use-handle-create-peer-connection.tsx
- src/features/call/hooks/socket/use-handle-doodle.tsx
- src/features/call/hooks/socket/use-handle-join-leave-call.tsx
- src/features/call/hooks/socket/use-handle-share-screen.tsx
- src/features/call/hooks/socket/use-handle-stream-my-video.ts
- src/features/call/hooks/socket/use-peer-event.tsx
- src/features/call/hooks/use-extract-text-from-stream.ts
- src/features/call/hooks/use-load-stream.ts
- src/features/call/store/participant.store.ts
- src/features/call/store/video-call.store.ts
- src/features/call/utils/get-stream-config.ts
- src/features/call/utils/peer-action.util.ts
- src/features/chat/rooms/hooks/use-join-call.ts
> fix toggle camera and mic

- src/features/call/components/call-bottom.tsx
- src/features/call/components/common/video-item.tsx
- src/features/call/components/receive-call.tsx
- src/features/call/hooks/socket/use-handle-stream-my-video.ts
- src/features/call/store/me.store.ts
Fix video loading spinner display
> Fix video loading spinner display

- src/features/call/components/common/focus-video-item.tsx
> Add video loading spinner

- src/features/call/hooks/socket/use-handle-share-screen.tsx
- src/features/call/video-call/components/actions/action-share-screen.tsx
- src/features/call/video-call/components/video/components/expand-video.tsx
- src/features/call/video-call/components/video/focus-video-item.tsx
- src/features/call/video-call/components/video/video-item.tsx
Refactor share screen handling and fix video item loading
> Refactor share screen handling and fix video item loading

- src/components/data-display/custom-tooltip/index.ts
- src/components/data-display/custom-tooltip/tooltip.tsx
- src/components/data-display/tooltip.tsx
- src/features/call/video-call/components/actions/action-add-members.tsx
- src/features/call/video-call/components/actions/action-chat.tsx
- src/features/call/video-call/components/actions/action-share-screen.tsx
- src/features/call/video-call/components/actions/action-toggle-camera.tsx
- src/features/call/video-call/components/actions/action-toggle-mic.tsx
- src/features/call/video-call/components/actions/leave-call.tsx
- src/features/call/video-call/components/chat-thread.tsx
- src/features/chat/components/chat-sidebar/chat-sidebar-header.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar.tsx
- src/features/chat/rooms/components/room-box/room-box-header/room-box-header.tsx
- src/features/chat/rooms/components/room-side/room-add-member.tsx
- Create a custom `Tooltip` component.
- reduce default `delayTime` of `Tooltip` to `100ms`.
- Add tooltips for actions on the Chat & Videocall features.
> Feature: Tooltips

- src/features/call/video-call/components/chat-thread.tsx
- src/features/call/video-call/components/video-call-header.tsx
- src/features/chat/components/chat-sidebar/chat-sidebar-header.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar.tsx
- src/features/chat/rooms/components/room-box/room-box-header/room-box-header.tsx
- src/features/chat/rooms/components/room-item/room-item.tsx
> Feature: update tooltip texts

- src/features/call/components/common/common.tsx
- src/features/call/components/common/modal/modal-choose-screen.tsx
- src/features/call/hooks/socket/use-handle-share-screen.tsx
- src/features/call/hooks/socket/use-handle-stream-my-video.ts
- src/features/call/store/video-call.store.ts
- src/features/call/utils/get-stream-config.ts
- src/features/call/utils/processing-stream.ts
- src/features/call/video-call/components/video-call-actions.tsx
> Add processing stream

- src/components/data-display/custom-tooltip/tooltip.tsx
- src/components/data-display/tooltip.tsx
- src/components/data-entry/search-input.tsx
- src/features/call/video-call/components/actions/action-add-members.tsx
- src/features/call/video-call/components/actions/action-chat.tsx
- src/features/call/video-call/components/actions/action-doodle.tsx
- src/features/call/video-call/components/actions/action-share-screen.tsx
- src/features/call/video-call/components/actions/action-toggle-camera.tsx
- src/features/call/video-call/components/actions/action-toggle-caption.tsx
- src/features/call/video-call/components/actions/action-toggle-layout.tsx
- src/features/call/video-call/components/actions/action-toggle-mic.tsx
- src/features/call/video-call/components/actions/dropdown-actions.tsx
- src/features/call/video-call/components/video-call-header.tsx
- src/features/chat/components/chat-setting.tsx
- src/features/chat/components/chat-sidebar/chat-sidebar-header.tsx
- src/features/chat/messages/components/message-editor/message-editor-text-input.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar-emoji.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar-file.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar-lang-control.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar-mic.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar.tsx
- src/features/chat/rooms/components/inbox/inbox.tsx
- src/features/chat/rooms/components/room-box/room-box-header/room-box-header.tsx
- src/features/chat/rooms/components/view-pin-button.tsx
- src/features/translate/components/extension.tsx
- src/features/translate/components/languages-control-bar/languages-control-bar.tsx
- src/features/translate/components/translate-option-bar/translate-option-bar.tsx
- src/hooks/use-keyboard-shortcuts.ts
- src/stores/shortcut-listen.store.ts
ticket: https://trello.com/c/tiiKK8uu/73-implement-shortcuts-and-tooltips-for-web
**Translation**
*  Swap Source & Target Languages (S)
*  Show/Hide Translated History (H)
*  Show/Hide Phrases (P)
*  Start/Stop Speech-to-text (Spacebar)
Conversation
*  New Conversation (Shift + N)
*  Show/Hide Conversation Setting (Shift + /)
*  Search (Shift + F)
*  Switch to “All” Tab (Shift + A)
*  Switch to “Group” Tab (Shift + G)
*  View Pinned Messages (Shift + P)
*  View Conversation Information (Shift + I)
*  Switch Input Language (Shift + L)
*  Upload files (Shift + U)
*  Start/Stop Speech to Text (Shift + Spacebar)
*  Open Emoji (Shift + ,)
*  Maximize/Minimize Middo Call (Shift + M)
**Conversation (Windows)**
*  New Conversation (Shift + N)
*  Show/Hide Conversation Setting (Shift + /)
* …
> Feature: Implement shortcuts for app

- src/components/data-entry/search-input.tsx
- src/features/call/video-call/components/actions/action-add-members.tsx
- src/features/call/video-call/components/actions/action-chat.tsx
- src/features/call/video-call/components/actions/action-doodle.tsx
- src/features/call/video-call/components/actions/action-share-screen.tsx
- src/features/call/video-call/components/actions/action-toggle-camera.tsx
- src/features/call/video-call/components/actions/action-toggle-caption.tsx
- src/features/call/video-call/components/actions/action-toggle-layout.tsx
- src/features/call/video-call/components/actions/action-toggle-mic.tsx
- src/features/call/video-call/components/actions/dropdown-actions.tsx
- src/features/call/video-call/components/video-call-header.tsx
- src/features/chat/components/chat-sidebar/chat-sidebar-header.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar-emoji.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar-file.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar-lang-control.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar-mic.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar.tsx
- src/features/chat/rooms/components/inbox/inbox.tsx
- src/features/chat/rooms/components/room-box/room-box-header/room-box-header.tsx
- src/features/chat/rooms/components/view-pin-button.tsx
- src/features/translate/components/languages-control-bar/languages-control-bar.tsx
- src/features/translate/components/translate-option-bar/translate-option-bar.tsx
- src/hooks/use-keyboard-shortcuts.ts
- Update `useKeyboardShortcut` hook to allow multiple shortcuts keySet
> feat: update useKeyboardSHortcut to allow multiple shortcuts

- src/features/call/video-call/components/actions/action-doodle.tsx
- src/features/call/video-call/components/actions/action-toggle-caption.tsx
- src/features/call/video-call/components/actions/action-toggle-layout.tsx
- src/features/call/video-call/components/actions/dropdown-actions.tsx
- src/features/call/video-call/components/video-call-header.tsx
- refactor shortcuts of actions on Middo call
- update wrong key-set of expanding Middo call.
> refactor: update Middo call actions shortcuts

- src/components/form/Input-crop-image.tsx
- src/features/user-settings/update-user-avatar.tsx
> Fix: expand upload avatar area

- package.json
- src/components/data-entry/input.tsx
- src/components/form/Input-field.tsx
- src/components/form/RHF/RHFFormItem/RHFFormItem.tsx
- src/components/form/RHF/RHFFormItem/index.ts
- src/components/form/RHF/RHFInputField/RHFInputField.tsx
- src/components/form/RHF/RHFInputField/index.ts
- src/components/ui/button.tsx
- src/components/ui/form.tsx
- src/components/ui/label.tsx
- src/configs/yup-form.ts
- src/features/user-settings/update-user-password.tsx
- src/hooks/use-keyboard-shortcuts.ts
- yarn.lock
- Add Form FormField, custom React-hook-form FormField with Input component
-  Update yup Schema and zod Schema to validate form
> Refactor form and fix bug update password

- src/features/call/video-call/components/actions/dropdown-actions.tsx
> fix: shortcuts on middo call

- src/components/actions/copy-zone-click.tsx
- src/features/chat/messages/components/message-editor/message-editor-text-input.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar.tsx
- src/features/chat/messages/components/message-editor/message-editor.tsx
- src/features/chat/messages/components/message-item/message-item-forward.tsx
> Fix: UI bugs

- src/features/chat/messages/components/message-editor/message-editor-text-input.tsx
Fix press Enter when message empty
> Fix press Enter when message empty

- src/features/chat/messages/components/message-editor/message-editor-text-input.tsx
- src/features/chat/messages/components/message-editor/message-editor-toolbar-translate.tsx
- src/features/chat/messages/components/message-editor/message-editor.tsx
- src/features/chat/messages/components/message-editor/translate-tool.tsx
- src/features/translate/hooks/use-translate.ts
* Add disable overlay on input
* Fix Save change after edit in Translate toolbar will remove text
> Fix translation bug and improve UI

- src/app/(main-layout)/(need-not-auth)/test-it-out/page.tsx
> chore: Fix useEffect dependency issue in TestItOut component

- src/features/chat/components/chat-sidebar/chat-sidebar.tsx
> fix conversation UI layout

- src/components/actions/long-press-menu.tsx
- src/components/chat-intro.tsx
- src/components/use-editor.ts
- src/features/chat/rooms/components/group-creator/group-creator.hook.ts
- src/features/chat/rooms/components/inbox/inbox-list.tsx
- src/features/chat/rooms/components/individual-create-side.tsx
- src/features/chat/rooms/components/pinned-room/pinned-room.tsx
- src/features/chat/rooms/components/room-box/room-typing.tsx
- src/features/chat/rooms/components/room-item/room-item-avatar.tsx
- src/features/chat/rooms/components/room-item/room-item-wrapper.tsx
- src/features/chat/rooms/components/room-item/room-item.tsx
- src/lib/i18n/lang/en.json
- src/lib/i18n/lang/ko.json
- src/lib/i18n/lang/vi.json
- Add UI display when have draft message in side chat
- Fix side chat in pinned not have online status
- Fix avatar display number of group
- Update style typing indicator
> Add draft message side chat

- src/features/call/hooks/socket/use-handle-create-peer-connection.tsx
- src/features/call/hooks/socket/use-handle-stream-my-video.ts
- src/features/call/hooks/socket/use-peer-event.tsx
- src/features/call/video-call/components/video/components/user-status.tsx
- src/features/call/video-call/components/video/components/video-item-text.tsx
- src/features/call/video-call/components/video/focus-video-item.tsx
- src/features/chat/rooms/components/room-item/room-item-coming-call.tsx
- src/utils/upload-img.ts
Refactor usePeerEvent and useHandleStreamMyVideo hooks Fix loading state in useHandleCreatePeerConnection hook Remove console log in VideoItemText component
> Fix button styling and add console log for file type

- src/app/help-desk/[businessId]/[...slugs]/_components/start-conversation/start-a-conversation.tsx
- src/app/help-desk/[businessId]/page.tsx
Reverts dudaji-vn/middo-translate#604
> Revert "Fix: start conversation component to include visitor data for user da…"

- src/features/chat/rooms/components/room-box/room-box-header/room-box-header.tsx
- src/providers/socket.provider.tsx
Add condition to check if the Visitor of Extension Room is online
> Feat/online status of visitor - room

- src/app/help-desk/[businessId]/[...slugs]/_components/start-conversation/start-a-conversation.tsx
- src/components/layout/header/help-desk-dropdown-menu.tsx
- src/features/chat/rooms/components/room-item/room-item-head.tsx
- src/utils/color-generator.tsx
> Fix: Add "?" bfore indicate tag-data when Search-Room don't return tag data

- src/app/(main-layout)/(protected)/spaces/[spaceId]/statistics/_components/report-dropdown/index.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/statistics/_components/report/report-chart/chart-filter-dropdown.tsx
This commit adds the ReportDropdown component following new UI style:
- For displaying dropdown menus in the statistics section of the application. 
- The component allows users to select options from a dropdown list and provides various customization options such as icons, labels, and current value display. It improves the user experience by providing a consistent and intuitive way to interact with dropdown menus throughout the application.
> feat: Add ReportDropdown component for displaying dropdown menus with new Styles

- src/app/(main-layout)/(protected)/spaces/[spaceId]/_components/business-sidebar/business-sidebar.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/statistics/_components/report/report-charts/languages-rank/language-rank.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/statistics/page.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/template.tsx
- src/app/globals.css
- src/features/business-spaces/space-navigator/space-navigator.tsx
- src/lib/i18n/lang/en.json
- src/lib/i18n/lang/ko.json
- src/lib/i18n/lang/vi.json
- src/stores/sidebar.store.ts
This commit modifies the SpaceNavigator component to enhance its functionality. It adds a dropdown menu and a button, allowing users to navigate between spaces more efficiently.
> feat: Update SpaceNavigator component base on the new Design.

- src/app/(main-layout)/(protected)/stations/_components/stations-list/station-card/station.tsx
- src/app/(main-layout)/(protected)/stations/_components/stations-list/work-stations/index.tsx
- src/app/(main-layout)/(protected)/stations/page.tsx
- src/app/(main-layout)/(protected)/stations/station-crud/sections/index.ts
- src/app/(main-layout)/(protected)/stations/station-crud/station-creation/create-station-header.tsx
- src/app/(main-layout)/(protected)/stations/station-crud/station-creation/create-station.tsx
- src/app/(main-layout)/(protected)/stations/station-crud/station-creation/index.ts
- src/app/(main-layout)/(protected)/stations/station-crud/station-deletion/delete-station-modal.tsx
- src/app/(main-layout)/(protected)/stations/station-crud/station-deletion/index.ts
- src/app/(main-layout)/(protected)/stations/station-crud/station-designation/index.ts
- src/app/(main-layout)/(protected)/stations/station-crud/station-designation/set-station-to-default.tsx
- src/app/(main-layout)/(protected)/stations/station-crud/station-edition/modal-set-default-station.tsx
- src/features/stations/hooks/use-get-spaces.ts
- src/features/stations/services/station.service.ts
- src/lib/i18n/lang/en.json
- src/lib/i18n/lang/ko.json
- src/lib/i18n/lang/vi.json
- src/services/station.service.ts
> feat: Update station creation, Add station-deletion and Station-set-as-default

- src/app/(main-layout)/(need-not-auth)/(layout-form)/sign-in/page.tsx
Refactor the sign-in page to improve the loading behavior and update the styling for better user experience. Replace the "ing" component with the "PageLoading" component to display a loading indicator when the page is loading or when the user is authenticated and the user data is available. Also, update the styling of the "Forgot Password" link to match the design specifications. These changes enhance the performance and visual appeal of the sign-in page.
> feat: Improve sign-in page loading and styling

- src/app/(main-layout)/(protected)/stations/_components/type.ts
- src/features/chat/components/chat-sidebar/chat-sidebar-tab-search.tsx
- src/features/chat/messages/components/forward-modal/forward-modal.tsx
- src/features/chat/rooms/api/index.ts
- src/features/chat/rooms/components/inbox/inbox-list.tsx
- src/features/chat/rooms/hooks/use-pin-room.ts
- src/features/recommendation/api/index.ts
- src/features/recommendation/hooks/index.tsx
> feat: Refactor rooms related `getting-endpoints` to accept either spaceId or stationId params

- src/features/chat/components/chat-sidebar/chat-sidebar-tab-search.tsx
- src/features/recommendation/api/index.ts
- src/features/recommendation/hooks/index.tsx
- src/features/search/api/index.ts
- src/hooks/use-search.ts
> chore: add missing commit to adjust endpoint api-get  recommendation

- src/app/(main-layout)/(protected)/spaces/[spaceId]/[conversationType]/_components/create-extension-shortcut.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/[conversationType]/page.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/template.tsx
- src/features/chat/messages/components/message-item/message-item-content.tsx
- src/features/chat/rooms/components/inbox/inbox-list.tsx
- src/features/chat/rooms/components/inbox/inbox.tsx
- src/features/chat/rooms/components/room-side/guest-information.tsx
- src/stores/space-inbox-filter.store.ts
chore: Update space template to set filter options and space data
fix: Update BusinessConversationPage to check for space extension
chore: Update unread notification revalidation
> feat: Update guest information, space template, empty extension check, unread ping-notification revalidation

- src/app/(main-layout)/(protected)/spaces/[spaceId]/scripts/_components/script-creation/create-chat-script-modal.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/scripts/_components/script-creation/schema.ts
- src/app/(main-layout)/(protected)/spaces/[spaceId]/scripts/_components/scripts-list/scripts-list.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/settings/_components/extension-creation/steps/script-chat-flow/custom-nodes/button-node.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/settings/_components/extension-creation/steps/script-chat-flow/custom-nodes/node-message-toolbar.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/settings/_components/extension-creation/steps/script-chat-flow/design-script-chat-flow.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/template.tsx
- src/components/attachment-selection.tsx
- src/components/media-light-box/media-light-box.tsx
- src/components/media-upload/media-upload-context.tsx
- src/features/chat/rooms/components/pinned-room/pinned-room.tsx
- src/features/conversation-scripts/hooks/use-create-or-edit-script.ts
- The UI keeps rerendering when open the edit script modal.
- The file removed has not been save to the script
> Fix: Script edit:  rerender issue

- src/app/(main-layout)/(protected)/stations/[stationId]/_components/station-navigator/station-navigator.tsx
- src/app/globals.css
- src/features/chat/components/chat-sidebar/chat-sidebar-header.tsx
- src/features/chat/components/chat-sidebar/chat-sidebar-tab-search.tsx
- src/features/chat/messages/components/message-box-search/message-box.tsx
- src/features/chat/messages/components/message-item/message-item.tsx
- src/features/chat/rooms/components/inbox/inbox-list.tsx
- src/features/chat/rooms/components/room-side/room-update-name.tsx
- src/features/chat/rooms/components/search-message-bar/search-message-bar.tsx
- src/features/search/components/search-tabs.tsx
- src/providers/app.provider.tsx
- Fix active search message UI
- Add more user interaction with the search bar
- Full search screen on mobile responsive
> Refactor search

- public/chat-widget.js
- src/app/help-desk/[businessId]/widget-notification/_components/NewMessageCatcher.tsx
- src/app/help-desk/[businessId]/widget-notification/page.tsx
Enable to update UI from embed page through window event
> feaure/send-message-fro-iframe-to-parent - Enable to update UI from embed page through window event

- src/app/(main-layout)/(protected)/spaces/[spaceId]/forms/_components/column-def/forms-columns.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/forms/_components/form-creation/create-form.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/forms/_components/form-creation/schema.ts
- src/app/(main-layout)/(protected)/spaces/[spaceId]/forms/page.tsx
This commit refactors the CreateOrEditBusinessForm component to handle form creation errors and display toast messages using the react-hot-toast library. It also adds the useBusinessNavigationData hook to consistently retrieve the spaceId required for form creation. Additionally, lazy loading functionality is implemented for form images in the CreateForm component, improving page load time. The form preview functionality is added to the CreateFormHeader component, allowing users to preview their forms before submission. SVG files are included for different form layouts, enhancing the visual representation of the forms. Finally, the ThankYouForm component is added to display a thank you message and optional image after form submission, providing visual feedback and confirmation. These …
> feat: Refactor form creation process and improve user experience

- src/app/(main-layout)/(protected)/spaces/[spaceId]/settings/_components/extension-creation/steps/script-chat-flow/custom-nodes/form-node.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/settings/_components/extension-creation/steps/script-chat-flow/custom-nodes/node-types.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/settings/_components/extension-creation/steps/script-chat-flow/custom-nodes/option-node.tsx
- src/app/(main-layout)/(protected)/spaces/[spaceId]/settings/_components/extension-creation/steps/script-chat-flow/design-script-chat-flow.tsx
- Modified the 'design-script-chat-flow.tsx' file to include 'form' as a new flow item type
- Updated the 'node-types.tsx' file to import and include the 'FormNode' component
- Modified the 'option-node.tsx' file to add a button to convert an option to a form node
Recent User Commits:
- feat: Update form page to display form submissions count
- feat: Update form page to display form submissions count
- feat: Update form page to display form submissions count
Recent Repository Commits:
- feat: Update form page to display form submissions count
- feat: Add optional media field to form field options
- feat: Refactor form creation process and improve user experience
> feat: Add 'form' as a new flow item type
